server:
  port: 8000
spring:
  application:
    name: scwProject
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowfunding_0511?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.188.147
    port: 6379

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/project/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  file:
    path: d:\log\scw-project   #日志文件存放路径
  level:
    com:
      offcn: debug   # error  info  debug

oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4FfAyMFbAvtoEaUXVhdw
  accessKeySecret: PdQdqksmKBQh5vBMCvErT3LWnvznip
  bucketName: scw20200907
  bucketDomain: scw20200907.oss-cn-beijing.aliyuncs.com